name: Go Test Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.2, 1.3, 1.4, 1.5, 1.6]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: ./test.sh
